### ISSUE TITLE
Use of depreciated methods from tibble

### ISSUE THREAD

**Issue by FabianErdm** [cran/xesreadR#1]
When using
`xesreadR::read_xes("mylog.xes")`

Warning messages:
1: `data_frame()` was deprecated in tibble 1.1.0.
ℹ Please use `tibble()` instead.
ℹ The deprecated feature was likely used in the xesreadR package.
  Please report the issue to the authors.

2: `as_data_frame()` was deprecated in tibble 2.0.0.
ℹ Please use `as_tibble()` instead.
ℹ The signature and semantics have changed, see `?as_tibble`.
ℹ The deprecated feature was likely used in the xesreadR package.
  Please report the issue to the authors.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by FabianErdm** [comment]
Sorry, wrong repo. Thank you for noticing
